---
apiVersion: v1
kind: ReplicationController
metadata:
  name: xiaoweb-service
  labels:
    name: xiaoweb-service
spec:
  replicas: 1
  selector:
    name: xiaoweb-service
  template:
    metadata:
      labels: 
        name: xiaoweb-service
    spec:
      containers:
      - name: xiaoweb-service
        image: 172.26.111.246:85/harbor/xiaoweb:PROJECT_VERSION
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
      
---
apiVersion: v1
kind: Service
metadata:
  name: xiaoweb-service
  labels: 
    name: xiaoweb-service
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: http
    nodePort: 30030
  selector:
    name: xiaoweb-pod
